"""Add day and meal_type to ShoppingItem

Revision ID: 0f3e8eb4d501
Revises: a8561dd09a61
Create Date: 2025-07-06 15:55:34.053971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3e8eb4d501'
down_revision = 'a8561dd09a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('meal_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_item', schema=None) as batch_op:
        batch_op.drop_column('meal_type')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
