"""Add last_nutrition_feedback to User

Revision ID: 4b5d40221ffb
Revises: f9ae16fdcfd4
Create Date: 2025-07-06 03:53:04.839743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5d40221ffb'
down_revision = 'f9ae16fdcfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_tip', schema=None) as batch_op:
        batch_op.drop_column('last_nutrition_feedback')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_nutrition_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_nutrition_feedback')

    with op.batch_alter_table('nutrition_tip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_nutrition_feedback', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
