"""Add snack to meal_type ENUM

Revision ID: 7c46604337f1
Revises: a958d294d5d7
Create Date: 2025-07-05 13:00:22.038727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c46604337f1'
down_revision = 'a958d294d5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('day',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
