"""Add diet_type and cuisine to Recipe

Revision ID: a958d294d5d7
Revises: ff5355272ecc
Create Date: 2025-07-05 09:11:38.142751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a958d294d5d7'
down_revision = 'ff5355272ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cuisine')
        batch_op.drop_column('diet_type')

    # ### end Alembic commands ###
