"""Add diet_type and cuisine to User

Revision ID: ff5355272ecc
Revises: 
Create Date: 2025-07-04 14:33:51.633393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5355272ecc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(length=50), nullable=True))
        batch_op.drop_column('dietary_pref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary_pref', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('cuisine')
        batch_op.drop_column('diet_type')

    # ### end Alembic commands ###
